import Head from 'next/head';
import Right from '../components/right'
import Picture from '../components/picture'
import About from '../components/about'
import Client from '../components/client'
import Project from '../components/project'
import Contact from '../components/contact'


export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head> */}
      <div className='h-screen overflow-hidden'>
        <main className='h-screen overflow-y-auto w-screen'>
          <Right />
          <Picture />
          <About />
          <Client />
          <Project />
          <Contact />
          
        </main>
      </div>
    </>
  );
}
